import { CoinData, LanguageCode, Theme } from "./types";

export const LANGUAGES: { code: LanguageCode; name: string; promptName: string; flag: string }[] = [
  { code: 'zh-TW', name: '中文', promptName: 'Traditional Chinese', flag: '🇹🇼' },
  { code: 'en', name: 'English', promptName: 'English', flag: '🇺🇸' },
  { code: 'ru', name: 'Русский', promptName: 'Russian', flag: '🇷🇺' },
  { code: 'ko', name: '한국어', promptName: 'Korean', flag: '🇰🇷' },
  { code: 'fr', name: 'Français', promptName: 'French', flag: '🇫🇷' },
  { code: 'id', name: 'Indonesia', promptName: 'Indonesian', flag: '🇮🇩' },
];

export const THEMES: Theme[] = [
  { 
    id: 'dark', 
    name: 'Cyber Dark', 
    colors: { bg: '#0B0E14', card: '#151A23', primary: '#10B981' } 
  },
  { 
    id: 'light', 
    name: 'Polar Light', 
    colors: { bg: '#F8FAFC', card: '#FFFFFF', primary: '#4F46E5' } 
  },
  { 
    id: 'midnight', 
    name: 'Midnight Dream', 
    colors: { bg: '#0F0c29', card: '#24243e', primary: '#a78bfa' } 
  },
  { 
    id: 'ocean', 
    name: 'Oceanic Depth', 
    colors: { bg: '#0f172a', card: '#1e293b', primary: '#38bdf8' } 
  },
  { 
    id: 'sunset', 
    name: 'Sunset Glow', 
    colors: { bg: '#1c1917', card: '#292524', primary: '#fb923c' } 
  }
];

export const TRANSLATIONS = {
  'zh-TW': {
    navTitle: 'CryptoSight',
    market: '市場',
    financing: '融資',
    intel: '情報',
    searchPlaceholder: '搜尋...',
    trending: '熱搜',
    marketOverview: '市場概況',
    asset: '資產',
    price: '價格',
    change: '漲跌',
    vol: '量',
    recentRaises: '近期融資 & ICO',
    source: '來源',
    projectSector: '項目 / 賽道',
    round: '輪次',
    amountVal: '金額 / 估值',
    investors: '投資人',
    details: '詳情',
    analysis: '分析',
    deepScan: '深度掃描',
    aiAnalyst: 'AI 分析師',
    askPlaceholder: '詢問關於',
    loading: '載入中...',
    chartDataUnavailable: '圖表數據不可用',
    priceAction7d: '價格走勢 (7天)',
    marketCap: '市值',
    volume24h: '交易量 (24h)',
    high24h: '最高 (24h)',
    low24h: '最低 (24h)',
    about: '關於',
    range24h: '24h 範圍',
    sentiment: '市場情緒',
    strategy: '策略',
    keyNarrative: '關鍵敘事',
    support: '支撐位',
    resistance: '壓力位',
    analysisComplete: '分析完成。以下是結構化報告：',
    analysisError: '無法生成分析報告。',
    aiGreeting: '你好！我是你的 AI 加密貨幣分析師。我可以為你分析 {coin} 的市場趨勢。',
    coinSwitched: '已切換至 {coin}。',
    bullish: '看漲',
    bearish: '看跌',
    neutral: '中立',
    rank: '排名',
    generatedBy: '由 AI 生成分析，非投資建議。',
    theme: '主題',
    entities: '實體追蹤',
    transactions: '即時異動',
    from: '發送方',
    to: '接收方',
    value: '價值',
    token: '代幣'
  },
  'en': {
    navTitle: 'CryptoSight',
    market: 'Market',
    financing: 'Financing',
    intel: 'Intel',
    searchPlaceholder: 'Search...',
    trending: 'Trending Now',
    marketOverview: 'Market Overview',
    asset: 'Asset',
    price: 'Price',
    change: 'Change',
    vol: 'Vol',
    recentRaises: 'Recent Raises & ICOS',
    source: 'Source',
    projectSector: 'Project / Sector',
    round: 'Round',
    amountVal: 'Amount / Val',
    investors: 'Investors',
    details: 'Details',
    analysis: 'Analysis',
    deepScan: 'Deep Scan',
    aiAnalyst: 'AI Analyst',
    askPlaceholder: 'Ask about',
    loading: 'Loading...',
    chartDataUnavailable: 'Chart Data Unavailable',
    priceAction7d: 'Price Action (7d)',
    marketCap: 'Market Cap',
    volume24h: 'Volume (24h)',
    high24h: 'High (24h)',
    low24h: 'Low (24h)',
    about: 'About',
    range24h: '24h Range',
    sentiment: 'Market Sentiment',
    strategy: 'Strategy',
    keyNarrative: 'Key Narrative',
    support: 'Support',
    resistance: 'Resistance',
    analysisComplete: 'Analysis Complete. Here is the structured report:',
    analysisError: 'Could not generate analysis report.',
    aiGreeting: 'Hello! I am your AI Crypto Analyst. I can analyze market trends for {coin}.',
    coinSwitched: 'Switched to {coin}.',
    bullish: 'Bullish',
    bearish: 'Bearish',
    neutral: 'Neutral',
    rank: 'Rank',
    generatedBy: 'AI Generated Analysis. Not Financial Advice.',
    theme: 'Theme',
    entities: 'Entities',
    transactions: 'Live Transactions',
    from: 'From',
    to: 'To',
    value: 'Value',
    token: 'Token'
  },
  'ru': {
    navTitle: 'CryptoSight',
    market: 'Рынок',
    financing: 'Финансы',
    intel: 'Разведка',
    searchPlaceholder: 'Поиск...',
    trending: 'В тренде',
    marketOverview: 'Обзор рынка',
    asset: 'Актив',
    price: 'Цена',
    change: 'Изм.',
    vol: 'Объем',
    recentRaises: 'Недавние сборы и ICO',
    source: 'Источник',
    projectSector: 'Проект / Сектор',
    round: 'Раунд',
    amountVal: 'Сумма / Оценка',
    investors: 'Инвесторы',
    details: 'Детали',
    analysis: 'Анализ',
    deepScan: 'Глуб. скан',
    aiAnalyst: 'AI Аналитик',
    askPlaceholder: 'Спросить о',
    loading: 'Загрузка...',
    chartDataUnavailable: 'Данные недоступны',
    priceAction7d: 'Цена (7д)',
    marketCap: 'Капитализация',
    volume24h: 'Объем (24ч)',
    high24h: 'Макс (24ч)',
    low24h: 'Мин (24ч)',
    about: 'О проекте',
    range24h: 'Диапазон 24ч',
    sentiment: 'Настроение',
    strategy: 'Стратегия',
    keyNarrative: 'Ключевой нарратив',
    support: 'Поддержка',
    resistance: 'Сопротивление',
    analysisComplete: 'Анализ завершен. Вот отчет:',
    analysisError: 'Не удалось создать отчет.',
    aiGreeting: 'Привет! Я твой крипто-аналитик. Я могу проанализировать тренды для {coin}.',
    coinSwitched: 'Переключено на {coin}.',
    bullish: 'Бычий',
    bearish: 'Медвежий',
    neutral: 'Нейтр.',
    rank: 'Ранг',
    generatedBy: 'Анализ создан ИИ. Не финансовый совет.',
    theme: 'Тема',
    entities: 'Сущности',
    transactions: 'Транзакции',
    from: 'От',
    to: 'Кому',
    value: 'Сумма',
    token: 'Токен'
  },
  'ko': {
    navTitle: 'CryptoSight',
    market: '시장',
    financing: '자금 조달',
    intel: '인텔',
    searchPlaceholder: '검색...',
    trending: '인기 급상승',
    marketOverview: '시장 개요',
    asset: '자산',
    price: '가격',
    change: '변동',
    vol: '거래량',
    recentRaises: '최근 모금 & ICO',
    source: '출처',
    projectSector: '프로젝트 / 섹터',
    round: '라운드',
    amountVal: '금액 / 가치',
    investors: '투자자',
    details: '상세',
    analysis: '분석',
    deepScan: '정밀 진단',
    aiAnalyst: 'AI 분석가',
    askPlaceholder: '질문하기',
    loading: '로딩 중...',
    chartDataUnavailable: '데이터 없음',
    priceAction7d: '가격 변동 (7일)',
    marketCap: '시가총액',
    volume24h: '거래량 (24시간)',
    high24h: '고가 (24시간)',
    low24h: '저가 (24시간)',
    about: '정보',
    range24h: '24시간 범위',
    sentiment: '시장 심리',
    strategy: '전략',
    keyNarrative: '핵심 서사',
    support: '지지선',
    resistance: '저항선',
    analysisComplete: '분석 완료. 구조화된 보고서입니다:',
    analysisError: '분석 보고서를 생성할 수 없습니다.',
    aiGreeting: '안녕하세요! AI 암호화폐 분석가입니다. {coin}의 시장 동향을 분석해 드릴 수 있습니다.',
    coinSwitched: '{coin}으로 전환되었습니다.',
    bullish: '상승세',
    bearish: '하락세',
    neutral: '중립',
    rank: '순위',
    generatedBy: 'AI가 생성한 분석입니다. 재정적 조언이 아닙니다.',
    theme: '테마',
    entities: '엔티티',
    transactions: '실시간 거래',
    from: '보낸 사람',
    to: '받는 사람',
    value: '가치',
    token: '토큰'
  },
  'fr': {
    navTitle: 'CryptoSight',
    market: 'Marché',
    financing: 'Financement',
    intel: 'Rens.',
    searchPlaceholder: 'Rechercher...',
    trending: 'Tendances',
    marketOverview: 'Aperçu du marché',
    asset: 'Actif',
    price: 'Prix',
    change: 'Var.',
    vol: 'Vol',
    recentRaises: 'Levées récentes & ICO',
    source: 'Source',
    projectSector: 'Projet / Secteur',
    round: 'Tour',
    amountVal: 'Montant / Val',
    investors: 'Investisseurs',
    details: 'Détails',
    analysis: 'Analyse',
    deepScan: 'Scan Profond',
    aiAnalyst: 'Analyste IA',
    askPlaceholder: 'Demander sur',
    loading: 'Chargement...',
    chartDataUnavailable: 'Données indisponibles',
    priceAction7d: 'Prix (7j)',
    marketCap: 'Cap. Marché',
    volume24h: 'Volume (24h)',
    high24h: 'Haut (24h)',
    low24h: 'Bas (24h)',
    about: 'À propos',
    range24h: 'Gamme 24h',
    sentiment: 'Sentiment',
    strategy: 'Stratégie',
    keyNarrative: 'Narratif Clé',
    support: 'Support',
    resistance: 'Résistance',
    analysisComplete: 'Analyse terminée. Voici le rapport :',
    analysisError: 'Impossible de générer le rapport.',
    aiGreeting: 'Bonjour ! Je suis votre analyste crypto IA. Je peux analyser les tendances pour {coin}.',
    coinSwitched: 'Passé à {coin}.',
    bullish: 'Haussier',
    bearish: 'Baissier',
    neutral: 'Neutre',
    rank: 'Rang',
    generatedBy: 'Analyse générée par IA. Pas un conseil financier.',
    theme: 'Thème',
    entities: 'Entités',
    transactions: 'Transactions',
    from: 'De',
    to: 'À',
    value: 'Valeur',
    token: 'Jeton'
  },
  'id': {
    navTitle: 'CryptoSight',
    market: 'Pasar',
    financing: 'Pendanaan',
    intel: 'Intel',
    searchPlaceholder: 'Cari...',
    trending: 'Tren Sekarang',
    marketOverview: 'Ikhtisar Pasar',
    asset: 'Aset',
    price: 'Harga',
    change: 'Perubahan',
    vol: 'Vol',
    recentRaises: 'Penggalangan Dana & ICO',
    source: 'Sumber',
    projectSector: 'Proyek / Sektor',
    round: 'Putaran',
    amountVal: 'Jumlah / Valuasi',
    investors: 'Investor',
    details: 'Detail',
    analysis: 'Analisis',
    deepScan: 'Pindai Dalam',
    aiAnalyst: 'Analis AI',
    askPlaceholder: 'Tanya tentang',
    loading: 'Memuat...',
    chartDataUnavailable: 'Data Grafik Tidak Tersedia',
    priceAction7d: 'Aksi Harga (7h)',
    marketCap: 'Kap Pasar',
    volume24h: 'Volume (24j)',
    high24h: 'Tinggi (24j)',
    low24h: 'Rendah (24j)',
    about: 'Tentang',
    range24h: 'Rentang 24j',
    sentiment: 'Sentimen Pasar',
    strategy: 'Strategi',
    keyNarrative: 'Narasi Utama',
    support: 'Dukungan',
    resistance: 'Resistensi',
    analysisComplete: 'Analisis Selesai. Ini laporannya:',
    analysisError: 'Tidak dapat membuat laporan analisis.',
    aiGreeting: 'Halo! Saya Analis Kripto AI Anda. Saya dapat menganalisis tren pasar untuk {coin}.',
    coinSwitched: 'Beralih ke {coin}.',
    bullish: 'Bullish',
    bearish: 'Bearish',
    neutral: 'Netral',
    rank: 'Peringkat',
    generatedBy: 'Analisis Dibuat AI. Bukan Saran Keuangan.',
    theme: 'Tema',
    entities: 'Entitas',
    transactions: 'Transaksi',
    from: 'Dari',
    to: 'Ke',
    value: 'Nilai',
    token: 'Token'
  },
};

const generateHistory = (basePrice: number, volatility: number) => {
  const history = [];
  let price = basePrice;
  for (let i = 0; i < 24; i++) {
    price = price * (1 + (Math.random() * volatility - volatility / 2));
    history.push({
      time: `${i}:00`,
      price: price
    });
  }
  return history;
};

export const COINS: CoinData[] = [
  {
    id: "bitcoin",
    symbol: "BTC",
    name: "Bitcoin",
    price: 64230.50,
    change24h: 2.4,
    volume: "32.1B",
    marketCap: "1.2T",
    history: generateHistory(64000, 0.02),
    description: "The first decentralized cryptocurrency. Store of value."
  },
  {
    id: "ethereum",
    symbol: "ETH",
    name: "Ethereum",
    price: 3450.12,
    change24h: -1.2,
    volume: "15.4B",
    marketCap: "400B",
    history: generateHistory(3500, 0.03),
    description: "Smart contract platform powering DeFi and NFTs."
  }
];

export const INITIAL_SYSTEM_PROMPT = `
You are CryptoSight AI, an elite cryptocurrency market analyst. 
Your tone is professional, concise, and data-driven, yet accessible.
You provide technical analysis, market sentiment analysis, and risk assessment.
When analyzing a coin, consider its price action, volume, and general market context.
Format your responses with clear markdown, using bold text for key figures.
If asked about investment advice, provide analysis but add a disclaimer that this is not financial advice.
`;